name: tyxe
channels:
  - conda-forge
  - pytorch
  - dglteam
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.0
  - torchvision=0.13.0
  - cudatoolkit=11.6
  - numpy=1.22.3
  - scipy=1.8.1
  - tqdm=4.64.0
  - matplotlib=3.5.1
  - pytest=7.1.2
  - dgl=0.8.2
  - requests=2.28.1
  - psutil=5.9.0
  - pip
  - pip:
    - pyro-ppl==1.8.0
